from enum import StrEnum


class ProviderType(StrEnum):
    LISTING_SOURCE = "LISTING_SOURCE"
    MARKETPLACE_SOURCE = "MARKETPLACE_SOURCE"
    BUYBACK_QUOTE_SOURCE = "BUYBACK_QUOTE_SOURCE"
    NEW_PRICE_ANCHOR = "NEW_PRICE_ANCHOR"


class SupportLevel(StrEnum):
    FULL_SUPPORT = "FULL_SUPPORT"
    PARTIAL_SUPPORT = "PARTIAL_SUPPORT"
    LIMITED_SUPPORT = "LIMITED_SUPPORT"
